[package]
name = "eyre"
version = "0.1.0"
authors = ["dave"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stable-eyre = "0.2.2"
structopt = "0.3.15"
